config/routes.rb
Rails.application.routes.draw do

  resources :room_users
  resources :room_messages
  resources :rooms

  root "home#index"


  devise_for :users

  resources :rents
  get '/rents/validation/:id', to: 'rents#valid_rent', as: 'valid_rent'

  resources :films
  get '/films/import', to: 'films#import', as: 'import_film'
  get '/film/add/:id', to: 'user_film#add_list', as: 'add_user_film'

  resources :contacts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



  scope '/user-film' do
    get '/', to: "user_film#index", as: 'user_film_index'
    delete '/:id', to: "user_film#delete", as: 'user_film_delete'
  end


  scope 'admin', module: 'admin', as: 'admin' do
    get '/dashboard', to: 'dashboard#index', as: 'dashboard'
    resources :users
    resources :rents
    resources :contacts
    resources :films
  end
end

app/views/layouts/admin/_header.html.erb
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= admin_dashboard_path %>">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">Videotheque Admin</div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <a class="nav-link" href="<%= admin_dashboard_path %>">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Utilisateurs
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link" href="<%= admin_users_path %>">
      <i class="fas fa-fw fa-chart-area"></i>
      <span>Utilisateurs</span></a>
  </li>

  <!-- Nav Item - Utilities Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link" href="<%= admin_contacts_path %>">
      <i class="fas fa-fw fa-chart-area"></i>
      <span>Contact</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Films
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link" href="<%= admin_rents_path %>">
      <i class="fas fa-fw fa-chart-area"></i>
      <span>Demande de location</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="<%= admin_films_path %>">
      <i class="fas fa-fw fa-chart-area"></i>
      <span>Films</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

</ul>

app/views/layouts/admin/base.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
  <title>App</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Cardio: Free One Page Template by Luka Cvetinovic</title>
  <meta name="description" content="Cardio is a free one page template made exclusively for Codrops by Luka Cvetinovic" />
  <meta name="keywords" content="html template, css, free, one page, gym, fitness, web design" />
  <meta name="author" content="Luka Cvetinovic for Codrops" />
  <meta name="msapplication-TileColor" content="#00a8ff">
  <meta name="msapplication-config" content="image/favicons/browserconfig.xml">
  <meta name="theme-color" content="#ffffff">

  <title>Videotheque Admin</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animsition/4.0.2/css/animsition.min.css">
  <!-- Custom fonts for this template -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0-beta.1/css/select2.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css" rel="stylesheet" type="text/css">
  <link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css">

  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="/styles/sb-admin-2.css">
  <!--===============================================================================================-->


  <%= stylesheet_pack_tag 'application' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body><!-- Page Wrapper -->
<div id="wrapper">
<%= render "layouts/admin/header" %>

<%= yield %>

<%= render "layouts/front_partials/footer" %>
</div>
</body>
</html>