config/routes.rb
Rails.application.routes.draw do

  resources :room_users
  resources :room_messages
  resources :rooms

  root "home#index"


  devise_for :users

  resources :rents
  get '/rents/validation/:id', to: 'rents#valid_rent', as: 'valid_rent'

  resources :films
  get '/films/import', to: 'films#import', as: 'import_film'
  get '/film/add/:id', to: 'user_film#add_list', as: 'add_user_film'

  resources :contacts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



  scope '/user-film' do
    get '/', to: "user_film#index", as: 'user_film_index'
    delete '/:id', to: "user_film#delete", as: 'user_film_delete'
  end


  scope 'admin', module: 'admin', as: 'admin' do
    get '/dashboard', to: 'dashboard#index', as: 'dashboard'
    resources :users
    resources :rents
    resources :contacts
    resources :films
  end
end

app/models/film.rb
class Film < ApplicationRecord

  has_many :films_users

  has_many :users, through: :films_users

end

app/controllers/admin/films_controller.rb
module Admin
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]

  # GET /films
  # GET /films.json
  def index
    page = params[:page].to_i
    @count = Film.all.count
    @start = (page - 5) * 15 < 0 ? 1 : page - 5
    @end = (page + 5) * 15 > @count ? @count / 15 : page + 5
    @films = Film.page(page).per(15)
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: 'Film was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    if user_signed_in?
      respond_to do |format|
        if current_user.role == 'ROLE_ADMIN'
          require 'csv'
          table = CSV.parse(File.read("storage/movies_metadata.csv"), headers: true)

          # genres = row[3]
          table.each do |row|
            film = Film.find_by(:title => row[8])

            if film === nil
              Film.create(
                  :adult => row[0],
                  :imdb_id => row[6],
                  :genres => row[3],
                  :runtime => row[16],
                  :title => row[8],
                  :description => row[9],
                  :thumbnail => row[11],
                  :realese_date => row[14]
              )
            end
          end
        end

        format.html { redirect_to films_url, notice: 'Film was successfully imported.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def film_params
      params.fetch(:film, {})
    end
end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]

  # GET /films
  # GET /films.json
  def index
    page = params[:page].to_i
    @count = Film.all.count
    @start = (page - 5) * 15 < 0 ? 1 : page - 5
    @end = (page + 5) * 15 > @count ? @count / 15 : page + 5
    @films = Film.page(page).per(15)
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: 'Film was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    if user_signed_in?
      respond_to do |format|
        if current_user.role == 'ROLE_ADMIN'
          require 'csv'
          table = CSV.parse(File.read("storage/movies_metadata.csv"), headers: true)

          # genres = row[3]
          table.each do |row|
            film = Film.find_by(:title => row[8])

            if film === nil
              Film.create(
                  :adult => row[0],
                  :imdb_id => row[6],
                  :genres => row[3],
                  :runtime => row[16],
                  :title => row[8],
                  :description => row[9],
                  :thumbnail => row[11],
                  :realese_date => row[14]
              )
            end
          end
        end

        format.html { redirect_to films_url, notice: 'Film was successfully imported.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def film_params
      params.fetch(:film, {})
    end
end

app/helpers/films_helper.rb
module FilmsHelper

  def notInList(id)
    if user_signed_in?
      inList = current_user.films.exists?(id)

      return !inList
    end
  end

end

app/views/films/_form.html.erb
<%= simple_form_for(@film) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<h1>Films</h1>
<div class="container">

  <table class="table table-striped table-hover">
    <thead>
    <tr>
      <th>Name</th>
      <th>Adulte ?</th>
      <th>Date de publication</th>
      <th>Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @films.each do |film| %>
      <tr>
        <td><%= film.title %></td>
        <td><%= film.adult ? "Non" : "Oui" %></td>
        <td><%= film.realese_date ? film.realese_date.strftime("%d-%m-%Y") : Time.now.strftime("%d/%m/%Y") %></td>
        <td><%= link_to 'Show', film %>
          <% if isSignedIn? and notInList(film.id) %>
            <%= link_to 'Ajout', add_user_film_path(film) %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <nav aria-label="Page navigation example">
    <% page = request.params[:page].to_i %>
    <% page = page == nil ? 0 : page %>
    <ul class="pagination">
      <li class="page-item
        <% if page == 1 %>disabled
        <% end %>"><a class="page-link" href="?page=<%= page -1 %>">Previous</a></li>
      <li class="page-item
        <% if page == 1 %>disabled
        <% end %>">
        <a class="page-link" href="?page=1" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
      <% for i in @start..@end do %>
        <li class="page-item
          <% if page == i || request.params[:page] == nil %>active disabled
          <% end %>"><a class="page-link" href="?page=<%= i %>"><%= i %></a></li>
      <% end %>
      <li class="page-item
        <% if page == @end %>disabled
        <% end %>">
        <a class="page-link" href="?page=<%= @count / 15 %>" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
      <li class="page-item
        <% if page == @end %>disabled
        <% end %>"><a class="page-link" href="?page=<%= page +1 %>">Next</a></li>
    </ul>
  </nav>

  <br>
  <% if isAdmin? %>
    <%= link_to 'New Film', new_film_path, class: 'btn btn-primary' %>
    <%= link_to 'Import Film', import_film_path, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/films/new.html.erb
<h1>New Film</h1>

<%= render 'form', film: @film %>

<% if isAdmin? %>
  <%= button_to 'Import', import_film_path, method: get %>
<% end %>
<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<section class="container">

<table class="table">
  <tr>
    <!--    <th>Name:</th>-->
    <!--    <td><%#= @user.lastname %> <%#= @user.firstname %></td>-->
  </tr>
  <tr>
    <th>Titre:</th>
    <td><%= @film.title %></td>
  </tr>
  <tr>
    <th>Durée:</th>
    <td><%= @film.runtime %></td>
  </tr>
  <tr>
    <th>Budget:</th>
    <td><%= @film.budget %></td>
  </tr>
  <tr>
    <th>Genres:</th>
    <td><%= @film.genres %></td>
  </tr>
  <tr>
    <th>Description:</th>
    <td><%= @film.description %></td>
  </tr>
  <tr>
    <th>Date de sortie:</th>
    <td>
      <% if @film.realese_date != nil %>
      <%= @film.realese_date.strftime("%d %m %Y") %>
        <% end %>
        </td>
  </tr>
</table>
<%= link_to 'Back', films_path %>
</section>