config/routes.rb
Rails.application.routes.draw do

  resources :room_users
  resources :room_messages
  resources :rooms

  root "home#index"


  devise_for :users

  resources :rents
  get '/rents/validation/:id', to: 'rents#valid_rent', as: 'valid_rent'

  resources :films
  get '/films/import', to: 'films#import', as: 'import_film'
  get '/film/add/:id', to: 'user_film#add_list', as: 'add_user_film'

  resources :contacts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



  scope '/user-film' do
    get '/', to: "user_film#index", as: 'user_film_index'
    delete '/:id', to: "user_film#delete", as: 'user_film_delete'
  end


  scope 'admin', module: 'admin', as: 'admin' do
    get '/dashboard', to: 'dashboard#index', as: 'dashboard'
    resources :users
    resources :rents
    resources :contacts
    resources :films
  end
end

app/views/layouts/front_partials/_footer.html.erb
<!-- Holder for mobile navigation -->
<div class="mobile-nav">
  <ul>
  </ul>
  <a href="#" class="close-link"><i class="arrow_up"></i></a>
</div>

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf-8" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.26.0/moment.min.js"></script>
<script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript" charset="utf-8" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-daterangepicker/3.0.5/daterangepicker.min.js"></script>
<script type="text/javascript" charset="utf-8" src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0-beta.1/js/select2.full.min.js"></script>


<!--<script src="/vendor/daterangepicker/daterangepicker.js"></script>-->
<!--===============================================================================================-->
<!--<script src="/vendor/countdowntime/countdowntime.js"></script>-->
<!--===============================================================================================-->
<!--<script src="/js/sb-admin-2.js"></script>-->

<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('table.datatable').DataTable();
        $('.select-two').select2({
            minimumInputLength : 3
        });

        $('#new_room_message').on('ajax:success', function(a, b,c ) {
            $(this).find('input[type="text"]').val('');
        });
    });
</script>

app/views/layouts/front_partials/_header.html.erb
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <%= link_to 'Videothèque', root_path, class: 'navbar-brand text-white' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link text-white" href="<%= films_path %>">
          <i class="fa fa-movie text-white"></i> Films
        </a>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link text-white" href="<%= user_film_index_url %>">
            <i class="fa fa-movie text-white"></i>Mes Films
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="<%= rents_path %>">
            <i class="fa fa-movie text-white"></i>Mes locations
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="<%= rooms_path %>">
            <i class="fa fa-movie text-white"></i>Chat
          </a>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to 'Contact', new_contact_path, class: 'nav-link text-white' %>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right"><!-- Dropdown -->
      <li class="nav-item dropdown">
        <a class="nav-link" href="#" id="navbardrop" data-toggle="dropdown">
          <i class="fa fa-user text-white"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <% if !user_signed_in? %>
            <%= link_to 'Connection', new_user_session_path, class: 'dropdown-item' %>
            <%= link_to 'Inscription', new_user_registration_path, class: 'dropdown-item' %>
          <% else %>
            <% if isAdmin? %>
              <%= link_to 'Dashboard', admin_dashboard_path, class: 'dropdown-item' %>
            <% end %>
            <%= link_to 'Profil', edit_user_registration_path, class: 'dropdown-item' %>
            <hr>
            <%= link_to 'Déconnection', destroy_user_session_path, class: 'dropdown-item', method: :delete %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

<% if notice %>
  <div class="alert alert-success alert-dismissible fade show w-50" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show w-50" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>