config/routes.rb
Rails.application.routes.draw do

  resources :room_users
  resources :room_messages
  resources :rooms

  root "home#index"


  devise_for :users

  resources :rents
  get '/rents/validation/:id', to: 'rents#valid_rent', as: 'valid_rent'

  resources :films
  get '/films/import', to: 'films#import', as: 'import_film'
  get '/film/add/:id', to: 'user_film#add_list', as: 'add_user_film'

  resources :contacts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



  scope '/user-film' do
    get '/', to: "user_film#index", as: 'user_film_index'
    delete '/:id', to: "user_film#delete", as: 'user_film_delete'
  end


  scope 'admin', module: 'admin', as: 'admin' do
    get '/dashboard', to: 'dashboard#index', as: 'dashboard'
    resources :users
    resources :rents
    resources :contacts
    resources :films
  end
end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :login

  has_many :rents
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :room_messages

  has_many :films_users
  has_many :films , through: :films_users

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable, :lockable, :timeoutable, :trackable

  validates :username, presence: true, uniqueness: {case_sensitive: false}, format: {with: /\A[a-zA-Z0-9 _\.]*\z/}

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup

    if login = conditions.delete(:login)
      where(conditions.to_hash).where("lower(username) = :value or lower(email) = :value", value: login.downcase).first
    else
      where(conditions.to_hash).first
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  load_and_authorize_resource
  layout 'layouts/admin/base'
  # GET /admin/users
  # GET /admin/users.json
  def index
    @users = User.all
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @user = User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/users/1
  # PATCH/PUT /admin/users/1.json
  def update

    if !user_params[:password].blank?
      @user.password = BCrypt::Password.create(user_params[:password])
    end

    @user.email = user_params[:email]
    @user.username = user_params[:username]
    @user.role = user_params[:role]

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email, :username, :password, :role)
  end
end

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, @user] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <span class="login100-form-title p-b-33">
						 <h2>Profil</h2>

					</span>
  <div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
    <%= f.input :email,
                required: false,
                autofocus: true,
                label: false,
                placeholder: "EMail",
                label_html: {class: 'hidden'},
                input_html: {
                    autocomplete: "Email",
                    class: 'input100'
                } %>
    <span class="focus-input100-1"></span>
    <span class="focus-input100-2"></span>
  </div>

  <div class="wrap-input100 rs1 validate-input" data-validate="Username not valid">
    <%= f.input :username,
                required: false,
                autofocus: true,
                label: false,
                placeholder: "Username",
                label_html: {class: 'hidden'},
                input_html: {
                    autocomplete: "Username",
                    class: 'input100'
                } %>
    <span class="focus-input100-1"></span>
    <span class="focus-input100-2"></span>
  </div>

  <div class="wrap-input100 rs1 validate-input" data-validate="Password not valid">
    <%= f.input :password,
                required: false,
                autofocus: true,
                label: false,
                hint: "we need your current password to confirm your changes",
                placeholder: "Mot de passe actuel",
                label_html: {class: 'hidden'},
                input_html: {
                    autocomplete: "Mot de passe actuel",
                    class: 'input100'
                } %>
    <span class="focus-input100-1"></span>
    <span class="focus-input100-2"></span>
  </div>

  <div class="wrap-input100 rs1 validate-input" data-validate="Password not valid">
    <select name="user[role]" id="role" class="form-control">
      <option value="ROLE_ADMIN" <% if @user.role == "ROLE_ADMIN" %> selected <% end %>>Admin</option>
      <option value="ROLE_USER" <% if @user.role == "ROLE_USER" %> selected <% end %>>Utilisteur</option>
    </select>
    <span class="focus-input100-1"></span>
    <span class="focus-input100-2"></span>
  </div>


  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success" %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<section class="container">
<h1>Editing Admin User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', admin_user_path(@user), class: "btn btn-primary" %> |
<%= link_to 'Back', admin_users_path, class: "btn btn-primary" %>
</section>

app/views/admin/users/index.html.erb
<section class="container">

<h1>Admin Users</h1>

<table class="table-striped table table-hover">
  <thead>
    <tr>
<!--      <td>Nom Prénom</td>-->
      <td>Email</td>
      <td>Username</td>
      <td>Créer le</td>
      <td>Dernière connection</td>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
<!--        <td><%#= user.lastname %> <%#= user.firstname %></td>-->
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= user.created_at.strftime("%d-%m-%Y") %></td>
        <td><%= user.last_sign_in_at ? user.last_sign_in_at.strftime("%d-%m-%Y") : ""%></td>
        <td><%= link_to 'Show', admin_user_path(user) %>
        <%= link_to 'Edit', edit_admin_user_path(user) %>
        <%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_admin_user_path %>
</section>

app/views/admin/users/new.html.erb
<section class="container">

<h1>New Admin User</h1>

  <%= render 'form', user: @user %>
  <%= link_to 'Back', admin_users_path, class: "btn btn-primary" %>
</section>

app/views/admin/users/show.html.erb
<section class="container mt-5">


<table class="table">
  <tr>
<!--    <th>Name:</th>-->
<!--    <td><%#= @user.lastname %> <%#= @user.firstname %></td>-->
  </tr>
  <tr>
    <th>Email:</th>
    <td><%= @user.email %></td>
  </tr>
  <tr>
    <th>username:</th>
    <td><%= @user.username %></td>
  </tr>
  <tr>
    <th>Créer le:</th>
    <td><%= @user.created_at.strftime("%d-%m-%Y") %></td>
  </tr>
  <tr>
    <th>Dernière connection le:</th>
    <td><%= @user.last_sign_in_at.strftime("%d-%m-%Y") %></td>
  </tr>
  <tr>
    <th>Role:</th>
    <td><%= @user.role %></td>
  </tr>
</table>

<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_user_path %>
</section>